language: php
php:
  - 5.6
  - 7.0

env:
  - TEST_SUITE=integration
  - TEST_SUITE=phpcs


script:
  - wget https://github.com/magento/magento2/archive/2.1.1.zip
  - unzip -qq 2.1.1.zip
  - cd magento2-2.1.1/
  - wget https://gist.githubusercontent.com/cdiacon/457f0e09fb936e5cc859/raw/a9d46ee07b550b9a742a3cb418c28b5d49b1753b/auth.json
  - composer require --prefer-source --no-interaction dotmailer/dotmailer-magento2-extension:dev-testing
  - sh -c "if [ '$TEST_SUITE' = 'integration' ]; then cd dev/tests/integration/; ./../../../vendor/bin/phpunit -c phpunit.xml.dist; fi"
  - sh -c "if [ '$TEST_SUITE' = 'phpcs' ]; then composer require --prefer-source --no-interaction "squizlabs/php_codesniffer=*" magento-ecg/coding-standard && vendor/squizlabs/php_codesniffer/scripts/phpcs --config-set installed_paths vendor/magento-ecg/coding-standard &&./vendor/squizlabs/php_codesniffer/scripts/phpcs -n --standard="EcgM2" ./vendor/dotmailer/dotmailer-magento2-extension/; fi"