<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="footer-copyright">
	<div class="container">
		<div class="main">
			<div class="col-xs-6">
				<small class="copyright">
					<span><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></span>
				</small>
			</div>
			<div class="col-xs-6">
				<small class="copyright">
					<ul class="list-inline text-right">
						<li><a href="/privacy-policy">Privacy Policy</a></li>
					</ul>
				</small>
			</div>
		</div>
	</div>
	<a href="#" id="backtotop"><span class="fa fa-angle-up"></span><span class="back-to-top"><?php echo __('Back to Top')?></span></a>
</div>