<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */ 

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$isLoggedIn = $customerSession->isLoggedIn();
$msg = $isLoggedIn ? __('Welcome') .', '. $customerSession->getCustomer()->getName() : $this->getWelcome() 
?>
<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header_notice')->toHtml();?>
<header class="page-header alothemes">
    <div class="header">
		<div class="header-top">
			<div class="container">
				<div class="row">
					<div class="content-logo col-lg-2 col-md-12 col-sm-12 col-xs-12">
						<div class="header-logo col-sm-4 col-xs-6">
							<?php echo $this->getChildHtml('logo'); ?>
						</div>
					</div>
					<div class="top-left text-center visible-lg col-lg-4">
						<p class="greet welcome-msg"><?php echo $msg; ?></p>
					</div>
					<div class="top-right col-md-6 col-sm-8 col-xs-12">
						<div class="content-search col-md-7 col-sm-8 hidden-xs hidden-sm">
							<div class="search-area header-search">
								<?php echo $this->getChildHtml('top.search'); ?>
							</div>
						</div>
						<div class="header-setting col-md-5">
							 <div class="top-links">
							 	<div class="hidden-sm pull-left">
							 		<?php echo $this->getChildHtml('header.links'); ?>
							 	</div>
							 	<?php echo $this->getChildHtml('minicart'); ?>
							 </div>
						</div>

						
					</div>
					<div class="text-center hidden-lg" style="clear:both;">
						<p class="greet welcome-msg"><?php echo $msg; ?></p>
					</div>
				</div>
			</div>
		</div>

		<div class="header-bottom header-sticker">
			<div class="container">
				<div class="row">
				    <div class="col-sm-12">
						<?php echo $this->getChildHtml('navigation.sections'); ?>
					</div>
					<div class="content-search col-xs-12 visible-xs visible-sm">
						<div class="search-area header-search">
							<?php echo $this->getChildHtml('top.search'); ?>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
