<?php
/**
 * @var \Fooman\PdfCustomiser\Block\Shipping $block
 */

$tracks = $block->getTracks();
$shippingDescription = $block->getShippingDescription();
?>
<?php echo $block->escapeHtml($shippingDescription) ?>
<?php if (count($tracks)) : ?>
    <?php foreach ($tracks as $track) : ?>
        <?php if ($track->getNumber()) : ?>
            <br/><?php echo $track->getTitle() ?> : <?php if ($block->shouldPrintTrackingBarcode()) {
                $barcodeParams = [
                    $block->escapeHtml($track->getNumber()),
                    $block->getBarcodeType(),
                    //the parameters below refer to x, y, width, and height of the barcode respectively
                    '', '', '35', '8'
                ]; ?>
                <tcpdf method="write1DBarcode" <?php echo $block->getEncodedParams($barcodeParams) ?>/><br/>
            <?php } else {
                echo $block->escapeHtml($track->getNumber());
            } ?>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>
