<?php
/**
 * @author     Kristof Ringleff
 * @package    Fooman_PdfCore
 * @copyright  Copyright (c) 2015 Fooman Limited (http://www.fooman.co.nz)
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * @var \Fooman\PdfCore\Block\Pdf\Template $block
 */
?>
<?php echo $block->getChildHtml('top') ?>
<?php echo $block->getChildHtml('main') ?>
<?php echo $block->getChildHtml('bottom') ?>


