<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile


?>
<div class="block newsletter block-subscribe">
    <div class="block-title"><strong>Newsletter</strong></div>
<!-- Start of signup -->
<script language="javascript">
<!--
function validate_signup(frm) {
	var emailAddress = frm.Email.value;
	var errorString = '';
	if (emailAddress == '' || emailAddress.indexOf('@') == -1) {
		errorString = 'Please enter your email address';
	}

    

	var isError = false;
    if (errorString.length > 0)
        isError = true;

    if (isError)
        alert(errorString);
	return !isError;
}


//-->
</script>

<form name="signup" id="signup" action="https://t.trackedlink.net/signup.ashx" method="post" onsubmit="return validate_signup(this)">
<p></p>
<input type="hidden" name="addressbookid" value="42464">
<!-- UserID - required field, do not remove -->
<input type="hidden" name="userid" value="130285">
<!-- ReturnURL - when the user hits submit, they'll get sent here -->
<input type="hidden" name="ReturnURL" value="https://shop.kintec.net/success">
<!-- Email - the user's email address -->

<div class="block-content">
	<div class="field newsletter input-box">
		<label class="label" for="newsletter"><span><?php /* @escapeNotVerified */ echo __('Sign Up for Our Newsletter:') ?></span></label>
		<div class="control">
			<input type="text" name="Email" id="newsletter" class="input-text" placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>" data-validate="{required:true, 'validate-email':true}">
			<input type="hidden" id="double" name="double" value="double"/>
		</div>
	</div>

	<div class="actions">
		<input class="action subscribe button" type="Submit" name="Submit" value="Subscribe">
	</div>
</form>
<!-- End of signup -->
</div>
