<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header $block
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$isLoggedIn = $customerSession->isLoggedIn();
$msg = $isLoggedIn ? __('Welcome') .', '. $customerSession->getCustomer()->getName() : $this->getWelcome() 
?>
<header class="page-header alothemes">
    <div class="header">
		<div class="header-top">
			<div class="container">
				<div class="row">
					<div class="top-left col-md-5 col-sm-5 col-xs-12">
						<p class="greet welcome-msg"><?php echo $msg; ?></p>
					</div>
					<div class="top-right col-md-7 col-sm-7 col-xs-12">
						<div class="header-setting">
							<div class="settting-switcher">
								<div class="dropdown-toggle">
									<div class="text-setting"><?php echo __('Links'); ?></div>
								</div>
								<div class="dropdown-switcher">
									<div class="top-links-alo">
										<div class="header-top-link">
											<?php echo $this->getChildHtml('header.links'); ?>
										</div>
									</div>
									<?php echo $this->getChildHtml('currency'); ?>
								    <?php echo $this->getChildHtml('store_language'); ?>
								</div>
							</div>
								<ul class="top-links">
								 <?php if( $isLoggedIn ) { ?>
								    <li>
										<a href="<?php echo $this->getUrl('customer/account/'); ?>" title="<?php echo __('My account') ?>"><?php echo __('My account') ?>
										</a>
									</li>
									<li>
									<span class="or"><?php echo __('Or') ?></span>
									</li>
								    <li class="logout">
										<a href="<?php echo $this->getUrl('customer/account/logout'); ?>" title="<?php echo __('Sign Out') ?>"><?php echo __('Sign Out') ?>
										</a>
									</li>
								 <?php } else { ?>
									<li class="login">
									  <a href="<?php echo $this->getUrl('customer/account/login'); ?>" title="<?php echo __('Sign In') ?>"><?php echo __('Sign In') ?>
									  </a>
									</li>
									<li>
										<span class="or"><?php echo __('Or') ?></span>
									</li>
									<li class="first">
										<a id="quick_sigup_link" style="positon:relative;" href="<?php echo $this->getUrl('customer/account/create'); ?>" title="<?php echo __('Register') ?>"><?php echo __('Register') ?>
										</a>
									</li>
								 <?php }  ?>
					            </ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="header-content header-sticker">
			<div class="container">
				<div class="row">
					<div class="content-logo col-md-2 col-sm-2 col-xs-12">
						<div class="header-logo">
							<?php echo $this->getChildHtml('logo'); ?>
						</div>
					</div>
					<div class="col-lg-12 header-right menu-mobile">
						<div class="content-cart pull-right">
						   <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
							<?php echo $this->getChildHtml('minicart'); ?>
						</div>
						<div class="header-setting content-seach">
							<div class="settting-switcher header-search">
								<div class="dropdown-toggle"><div class="icon-setting"><i class="icon-magnifier icons"></i></div></div>
								<div class="dispaly-seach dropdown-switcher">
									<div class="search-area header-search">
										<?php echo $this->getChildHtml('top.search'); ?>
									</div>
								</div>
						    </div>
						</div>
						<?php echo $this->getChildHtml('navigation.sections'); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>
