<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<style>
.catalog-product-view .modal-content div {
    text-align: left;
}

 .catalog-product-view .modal-popup .swatch-attribute.colour{
    height: auto;
    min-height: auto;
 }

 .catalog-product-view .modal-popup .swatch-attribute-options {
    display: block;
}

.modal-popup .addit{
    display:none;
}
</style>
<div class="box-tocart">
    <?php
        $_finalsale = $_product->getResource()->getAttribute('warehouse_final_sale')->getFrontend()->getValue($_product);

        if($_finalsale == 'Yes') { ?>
            <p class="clearance-notice">* ALL WAREHOUSE CLEARANCE ITEMS ARE A FINAL SALE</p>
        <?php } 
    ?>
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
		    <div class="product-qty">
				<label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
				<div class="control custom-qty">
					 <button  type="button" class="reduced items" onclick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty ) && qty > 1 ) result.value--;return false;">
						<i class="fa fa-minus-square-o"></i>
					</button>
					<input type="number"
						   name="qty"
						   id="qty"
						   maxlength="12"
						   value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
						   title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
						   data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
						   />
					 <button  type="button" class="increase items" onclick="var result = document.getElementById('qty'); var qty = result.value; if( !isNaN( qty )) result.value++;return false;">
						<i class="fa fa-plus-square-o"></i>
					</button>		   
				</div>
			</div>
        </div>
        <?php endif; ?>
        <div class="actions add-to-cart">
            <button type="button"
                    title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                    class="action primary tocart button btn-cart"
                    id="product-addtocart-button">
                <span>Add to bag</span>
            </button>
            <?php echo $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        'Magento_Catalog/js/catalog-add-to-cart'
    ], function ($,modal) {
        'use strict';
        var formOpen = false;
        $('#product-addtocart-button').click(function(){
            var dishoptions = {
                    type: 'popup',
                    responsive: true,
                    innerScroll: true,
                    title: 'Product',
                    buttons: false,
                    closed:function(){
                        
                        $('#product-add-form-container').append($('.product-add-form'));
                    }
                };
                if(!$('#product_addtocart_form').valid()){
                    formOpen = true;
                    var popup = modal(dishoptions, $('.product-add-form'));
                    $('.product-add-form').modal('openModal'); 
                    return false;
                }
                if(formOpen)
                    $('.product-add-form').modal('closeModal'); 
                $('#product_addtocart_form').submit();
           
        });
        $('#product_addtocart_form').mage('validation', {
            radioCheckboxClosest: '.nested',
            submitHandler: function (form) {
                
                 
                var widget = $(form).catalogAddToCart({
                    bindSubmit: false
                });
                widget.catalogAddToCart('submitForm', $(form));

                return false;
            }
        });
    });
</script>
<?php endif; ?>